apiVersion: v1
kind: Service
metadata:
  name: go-microservice-template
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30007
  selector:
    app: go-microservice-template
