version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.17

    steps:
      - checkout
      - run:
          name: Build Go microservice
          command: |
            go build
            go test ./...

