jobs:
  build:
    docker:
      - image: golang:1.17

    steps:
      - checkout
      - run:
          name: Build Go microservice
          command: |
            go build
            go test ./...
      - run:
          name: Build Docker image
          command: |
            docker build -t awallenjr83/go-microservice-template .
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push awallenjr83/go-microservice-template

